name: Build Docs

on: 
  push:
    branches: 
      - master

jobs:
    build:
        runs-on: windows-latest
        
        steps:
        - uses: actions/checkout@v2

        - name: Build the docs
            shell: cmd
            working-directory: docs-source/
            run: ..\packages\docfx.console.2.48.0\tools\docfx.exe docfx_CLI.json

        - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./_site